export const SET_BOOK_VIEW = "SET_BOOK_VIEW";
export const FETCH_BOOKS_REQUEST = "FETCH_BOOKS_REQUEST";
export const FETCH_BOOKS_SUCCESS = "FETCH_BOOKS_SUCCESS";
export const FETCH_BOOKS_FAILURE = "FETCH_BOOKS_FAILURE";
export const FETCH_STORAGE_BOOKS = "FETCH_STORAGE_BOOKS";
export const ADD_NEW_BOOK = "ADD_NEW_BOOK";
export const EDIT_BOOK = "EDIT_BOOK";
